version: '3.7'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      - 8898:8898
    env_file:
      - ./.env.local
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres_data:
